version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mafia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV: dev
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN_DEV}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: >
      sh -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  voice-server:
    build:
      context: ./voice-server
      dockerfile: Dockerfile.dev
    environment:
      MEDIASOUP_WORKERS: 2
    ports:
      - "4443:4443"
      - "30000-30010:30000-30010/udp"

volumes:
  postgres_data:
  redis_data: