# docker/docker-compose.local.yml
# Local stack with centralized env files (config/env/.env.local)

services:
  # TON Local Mock Server
  ton-local:
    build:
      context: ./ton-local
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # API port
      - "8082:8082"  # Explorer port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-local:
    image: postgres:15-alpine
    env_file:
      - ../config/env/.env.local
    ports:
      - "5433:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-local:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_local_data:/data

  rabbitmq-local:
    image: rabbitmq:3-management-alpine
    env_file:
      - ../config/env/.env.local
    ports:
      - "5673:5672"
      - "15673:15672"  # Management UI
    volumes:
      - rabbitmq_local_data:/var/lib/rabbitmq

  backend-local:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.local
    volumes:
      - ..:/app
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "8001:8000"
    depends_on:
      postgres-local:
        condition: service_healthy
      redis-local:
        condition: service_started
      rabbitmq-local:
        condition: service_started
      ton-local:
        condition: service_started
    command: >
      sh -c "
        alembic upgrade head &&
        python scripts/init_local_data.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  celery-local:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.local
    volumes:
      - ..:/app
    depends_on:
      - redis-local
      - rabbitmq-local
      - postgres-local
    command: celery -A app.core.celery:celery_app worker --loglevel=debug

  celery-beat-local:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.local
    volumes:
      - ..:/app
    depends_on:
      - redis-local
      - rabbitmq-local
      - postgres-local
    command: celery -A app.core.celery:celery_app beat --loglevel=debug

volumes:
  postgres_local_data:
  redis_local_data:
  rabbitmq_local_data:
