version: "3.9"

# Staging stack (production-like) with centralized env files (config/env/.env.staging)
# Uses prebuilt images pulled from registry.
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - ../config/env/.env.staging
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_staging_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ../config/env/.env.staging
    ports:
      - "15672:15672" # expose mgmt if needed
    volumes:
      - rabbitmq_staging_data:/var/lib/rabbitmq

  backend:
    image: ${DOCKER_REGISTRY:-your-registry.com}/mafia-backend:staging
    env_file:
      - ../config/env/.env.staging
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "8000:8000" # expose for QA or behind reverse-proxy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery:
    image: ${DOCKER_REGISTRY:-your-registry.com}/mafia-backend:staging
    env_file:
      - ../config/env/.env.staging
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: celery -A app.core.celery:celery_app worker --loglevel=info

  celery-beat:
    image: ${DOCKER_REGISTRY:-your-registry.com}/mafia-backend:staging
    env_file:
      - ../config/env/.env.staging
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: celery -A app.core.celery:celery_app beat --loglevel=info

  voice:
    image: ${DOCKER_REGISTRY:-your-registry.com}/mafia-voice:staging
    env_file:
      - ../config/env/.env.staging
    ports:
      - "4443:4443"
      - "30000-30010:30000-30010/udp"

volumes:
  postgres_staging_data:
  redis_staging_data:
  rabbitmq_staging_data:
