version: "3.9"

# Development (testnet) stack with centralized env files (config/env/.env.dev)
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - ../config/env/.env.dev
    ports:
      - "5434:5432" # optional: подключение с хоста
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ../config/env/.env.dev
    ports:
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.dev
    volumes:
      - ..:/app
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.dev
    volumes:
      - ..:/app
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: celery -A app.core.celery:celery_app worker --loglevel=info

  celery-beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../config/env/.env.dev
    volumes:
      - ..:/app
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: celery -A app.core.celery:celery_app beat --loglevel=info

  voice:
    build:
      context: ../voice-server
      dockerfile: Dockerfile
    env_file:
      - ../config/env/.env.dev
    ports:
      - "4443:4443"
      - "30000-30010:30000-30010/udp"

volumes:
  postgres_dev_data:
  redis_dev_data:
  rabbitmq_dev_data:
