"""init_tables

Revision ID: 1505d43d4d74
Revises: 
Create Date: 2025-08-18 23:12:42.109033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1505d43d4d74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_actions_game_id'), 'game_actions', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_actions_player_id'), 'game_actions', ['player_id'], unique=False)
    op.create_table('game_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.Column('mafia_count', sa.Integer(), nullable=False),
    sa.Column('mvp_player_id', sa.String(), nullable=True),
    sa.Column('most_active_player_id', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_stats_game_id'), 'game_stats', ['game_id'], unique=True)
    op.create_table('social_friendships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('friend_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_friendships_friend_id'), 'social_friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_social_friendships_user_id'), 'social_friendships', ['user_id'], unique=False)
    op.create_table('social_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_user', sa.String(), nullable=False),
    sa.Column('to_user', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_interactions_from_user'), 'social_interactions', ['from_user'], unique=False)
    op.create_index(op.f('ix_social_interactions_game_id'), 'social_interactions', ['game_id'], unique=False)
    op.create_index(op.f('ix_social_interactions_to_user'), 'social_interactions', ['to_user'], unique=False)
    op.create_table('social_user_stats',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('likes_received', sa.Integer(), nullable=False),
    sa.Column('likes_given', sa.Integer(), nullable=False),
    sa.Column('gifts_received', sa.Integer(), nullable=False),
    sa.Column('gifts_sent', sa.Integer(), nullable=False),
    sa.Column('reports_received', sa.Integer(), nullable=False),
    sa.Column('reports_sent', sa.Integer(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('linguistic_ratings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skins_skin_id'), 'user_skins', ['skin_id'], unique=False)
    op.create_index(op.f('ix_user_skins_user_id'), 'user_skins', ['user_id'], unique=False)
    op.create_table('voice_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_participants_room_id'), 'voice_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_voice_participants_user_id'), 'voice_participants', ['user_id'], unique=False)
    op.create_table('voice_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_rooms_game_id'), 'voice_rooms', ['game_id'], unique=False)
    op.alter_column('auth_users', 'language_code',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'allows_write_to_pm',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'rating',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'country',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'spoken_languages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'purchased_languages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'games_played',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'games_won',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'linguistic_rating',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auth_users', 'banned_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('auth_users', 'muted_players',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('auth_users_telegram_id_key', 'auth_users', type_='unique')
    op.drop_index('ix_auth_users_telegram_id', table_name='auth_users')
    op.create_index(op.f('ix_auth_users_telegram_id'), 'auth_users', ['telegram_id'], unique=True)
    op.alter_column('economy_pending_withdrawals', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_pending_withdrawals', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_token_prices', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('economy_transactions', 'is_onchain',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_transactions', 'confirmations',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_transactions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'balance_offchain',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'balance_onchain',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'total_earned',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'total_spent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'total_withdrawn',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'last_claim_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('economy_wallets', 'streak_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'withdrawal_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('economy_wallets', 'require_2fa',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('economy_wallets_user_id_key', 'economy_wallets', type_='unique')
    op.drop_index('ix_economy_wallets_user_id', table_name='economy_wallets')
    op.create_index(op.f('ix_economy_wallets_user_id'), 'economy_wallets', ['user_id'], unique=True)
    op.alter_column('game_games', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_games', 'phase',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_games', 'day_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('game_games', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('game_players', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_players', 'alive',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_players', 'kicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('game_players', 'stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_game_players_user_id'), 'game_players', ['user_id'], unique=False)
    op.alter_column('skins_catalog', 'is_limited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skins_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skins_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skins_catalog', 'is_limited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_game_players_user_id'), table_name='game_players')
    op.alter_column('game_players', 'stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('game_players', 'kicked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('game_players', 'alive',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('game_players', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'citizen'::character varying"),
               existing_nullable=False)
    op.alter_column('game_games', 'ended_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('game_games', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('game_games', 'day_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_games', 'phase',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'lobby'::character varying"),
               existing_nullable=False)
    op.alter_column('game_games', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'lobby'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_economy_wallets_user_id'), table_name='economy_wallets')
    op.create_index('ix_economy_wallets_user_id', 'economy_wallets', ['user_id'], unique=False)
    op.create_unique_constraint('economy_wallets_user_id_key', 'economy_wallets', ['user_id'])
    op.alter_column('economy_wallets', 'require_2fa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'withdrawal_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'streak_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'last_claim_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('economy_wallets', 'total_withdrawn',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'total_spent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'total_earned',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'balance_onchain',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('economy_wallets', 'balance_offchain',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_transactions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=False)
    op.alter_column('economy_transactions', 'confirmations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_transactions', 'is_onchain',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('economy_token_prices', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('economy_pending_withdrawals', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('economy_pending_withdrawals', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_users_telegram_id'), table_name='auth_users')
    op.create_index('ix_auth_users_telegram_id', 'auth_users', ['telegram_id'], unique=False)
    op.create_unique_constraint('auth_users_telegram_id_key', 'auth_users', ['telegram_id'])
    op.alter_column('auth_users', 'muted_players',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('auth_users', 'banned_until',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('auth_users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auth_users', 'linguistic_rating',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('auth_users', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('auth_users', 'games_won',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('auth_users', 'games_played',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('auth_users', 'purchased_languages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('auth_users', 'spoken_languages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('auth_users', 'country',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'US'::character varying"),
               existing_nullable=False)
    op.alter_column('auth_users', 'rating',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1000'),
               existing_nullable=False)
    op.alter_column('auth_users', 'allows_write_to_pm',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auth_users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auth_users', 'language_code',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_voice_rooms_game_id'), table_name='voice_rooms')
    op.drop_table('voice_rooms')
    op.drop_index(op.f('ix_voice_participants_user_id'), table_name='voice_participants')
    op.drop_index(op.f('ix_voice_participants_room_id'), table_name='voice_participants')
    op.drop_table('voice_participants')
    op.drop_index(op.f('ix_user_skins_user_id'), table_name='user_skins')
    op.drop_index(op.f('ix_user_skins_skin_id'), table_name='user_skins')
    op.drop_table('user_skins')
    op.drop_table('social_user_stats')
    op.drop_index(op.f('ix_social_interactions_to_user'), table_name='social_interactions')
    op.drop_index(op.f('ix_social_interactions_game_id'), table_name='social_interactions')
    op.drop_index(op.f('ix_social_interactions_from_user'), table_name='social_interactions')
    op.drop_table('social_interactions')
    op.drop_index(op.f('ix_social_friendships_user_id'), table_name='social_friendships')
    op.drop_index(op.f('ix_social_friendships_friend_id'), table_name='social_friendships')
    op.drop_table('social_friendships')
    op.drop_index(op.f('ix_game_stats_game_id'), table_name='game_stats')
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_game_actions_player_id'), table_name='game_actions')
    op.drop_index(op.f('ix_game_actions_game_id'), table_name='game_actions')
    op.drop_table('game_actions')
    # ### end Alembic commands ###