"""init tables

Revision ID: a1624953c4c4
Revises: 
Create Date: 2025-08-24 13:34:52.871594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1624953c4c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('allows_write_to_pm', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('spoken_languages', sa.JSON(), nullable=False),
    sa.Column('purchased_languages', sa.JSON(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('linguistic_rating', sa.JSON(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('skin_id', sa.String(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('muted_players', sa.JSON(), nullable=False),
    sa.Column('referrer_id', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_auth_users_telegram_id'), 'auth_users', ['telegram_id'], unique=True)
    op.create_table('economy_pending_withdrawals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('ton_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economy_pending_withdrawals_user_id'), 'economy_pending_withdrawals', ['user_id'], unique=False)
    op.create_table('economy_token_prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_ton', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economy_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_onchain', sa.Boolean(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('tx_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economy_transactions_tx_hash'), 'economy_transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_economy_transactions_user_id'), 'economy_transactions', ['user_id'], unique=False)
    op.create_table('economy_wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ton_address', sa.String(), nullable=False),
    sa.Column('jetton_wallet', sa.String(), nullable=False),
    sa.Column('encrypted_mnemonic', sa.Text(), nullable=False),
    sa.Column('balance_offchain', sa.Integer(), nullable=False),
    sa.Column('balance_onchain', sa.Float(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('total_withdrawn', sa.Integer(), nullable=False),
    sa.Column('last_claim_at', sa.DateTime(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('withdrawal_enabled', sa.Boolean(), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jetton_wallet'),
    sa.UniqueConstraint('ton_address')
    )
    op.create_index(op.f('ix_economy_wallets_user_id'), 'economy_wallets', ['user_id'], unique=True)
    op.create_table('game_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_actions_game_id'), 'game_actions', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_actions_player_id'), 'game_actions', ['player_id'], unique=False)
    op.create_table('game_games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('day_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('winner_team', sa.String(), nullable=True),
    sa.Column('main_winner_team', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('death_reason', sa.String(), nullable=True),
    sa.Column('death_day', sa.Integer(), nullable=True),
    sa.Column('kicked_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_players_user_id'), 'game_players', ['user_id'], unique=False)
    op.create_table('game_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.Column('mafia_count', sa.Integer(), nullable=False),
    sa.Column('mvp_player_id', sa.String(), nullable=True),
    sa.Column('most_active_player_id', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_stats_game_id'), 'game_stats', ['game_id'], unique=True)
    op.create_table('skins_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price_mafia', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('is_limited', sa.Boolean(), nullable=False),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_friendships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('friend_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_friendships_friend_id'), 'social_friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_social_friendships_user_id'), 'social_friendships', ['user_id'], unique=False)
    op.create_table('social_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_user', sa.String(), nullable=False),
    sa.Column('to_user', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_interactions_from_user'), 'social_interactions', ['from_user'], unique=False)
    op.create_index(op.f('ix_social_interactions_game_id'), 'social_interactions', ['game_id'], unique=False)
    op.create_index(op.f('ix_social_interactions_to_user'), 'social_interactions', ['to_user'], unique=False)
    op.create_table('social_user_stats',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('likes_received', sa.Integer(), nullable=False),
    sa.Column('likes_given', sa.Integer(), nullable=False),
    sa.Column('gifts_received', sa.Integer(), nullable=False),
    sa.Column('gifts_sent', sa.Integer(), nullable=False),
    sa.Column('reports_received', sa.Integer(), nullable=False),
    sa.Column('reports_sent', sa.Integer(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('linguistic_ratings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skins_skin_id'), 'user_skins', ['skin_id'], unique=False)
    op.create_index(op.f('ix_user_skins_user_id'), 'user_skins', ['user_id'], unique=False)
    op.create_table('voice_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_participants_room_id'), 'voice_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_voice_participants_user_id'), 'voice_participants', ['user_id'], unique=False)
    op.create_table('voice_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_rooms_game_id'), 'voice_rooms', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_rooms_game_id'), table_name='voice_rooms')
    op.drop_table('voice_rooms')
    op.drop_index(op.f('ix_voice_participants_user_id'), table_name='voice_participants')
    op.drop_index(op.f('ix_voice_participants_room_id'), table_name='voice_participants')
    op.drop_table('voice_participants')
    op.drop_index(op.f('ix_user_skins_user_id'), table_name='user_skins')
    op.drop_index(op.f('ix_user_skins_skin_id'), table_name='user_skins')
    op.drop_table('user_skins')
    op.drop_table('social_user_stats')
    op.drop_index(op.f('ix_social_interactions_to_user'), table_name='social_interactions')
    op.drop_index(op.f('ix_social_interactions_game_id'), table_name='social_interactions')
    op.drop_index(op.f('ix_social_interactions_from_user'), table_name='social_interactions')
    op.drop_table('social_interactions')
    op.drop_index(op.f('ix_social_friendships_user_id'), table_name='social_friendships')
    op.drop_index(op.f('ix_social_friendships_friend_id'), table_name='social_friendships')
    op.drop_table('social_friendships')
    op.drop_table('skins_catalog')
    op.drop_index(op.f('ix_game_stats_game_id'), table_name='game_stats')
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_game_players_user_id'), table_name='game_players')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_table('game_games')
    op.drop_index(op.f('ix_game_actions_player_id'), table_name='game_actions')
    op.drop_index(op.f('ix_game_actions_game_id'), table_name='game_actions')
    op.drop_table('game_actions')
    op.drop_index(op.f('ix_economy_wallets_user_id'), table_name='economy_wallets')
    op.drop_table('economy_wallets')
    op.drop_index(op.f('ix_economy_transactions_user_id'), table_name='economy_transactions')
    op.drop_index(op.f('ix_economy_transactions_tx_hash'), table_name='economy_transactions')
    op.drop_table('economy_transactions')
    op.drop_table('economy_token_prices')
    op.drop_index(op.f('ix_economy_pending_withdrawals_user_id'), table_name='economy_pending_withdrawals')
    op.drop_table('economy_pending_withdrawals')
    op.drop_index(op.f('ix_auth_users_telegram_id'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###